version: '3.8'
services:
  ingestion:
    build: ../services/ingestion_service
    ports:
      - "8001:8000"
  nlp:
    build: ../services/nlp_service
    ports:
      - "8002:8000"
  vision:
    build: ../services/vision_service
    ports:
      - "8003:8000"
  fusion:
    build: ../services/fusion_service
    ports:
      - "8004:8000"
  ethics:
    build: ../services/ethics_service
    ports:
      - "8005:8000"
